// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth').default>>>>
    }
    '/api/fields': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fields').default>>>>
    }
    '/api/teams': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}