// Generated by nuxi
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="vuetify-nuxt-module" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference types="@pinia/nuxt" />
/// <reference types="vuetify" />
/// <reference types="vuetify-nuxt-module/custom-configuration" />
/// <reference types="vuetify-nuxt-module/configuration" />
/// <reference path="../node_modules/vuetify-nuxt-module/dist/runtime/plugins/types" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
