// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6.11.2024, 17:10:35
const configMerger = require("/home/projects/sb1-j5plsr/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/projects/sb1-j5plsr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/plugins/**/*.{js,ts,mjs}","/home/projects/sb1-j5plsr/composables/**/*.{js,ts,mjs}","/home/projects/sb1-j5plsr/utils/**/*.{js,ts,mjs}","/home/projects/sb1-j5plsr/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-j5plsr/app.config.{js,ts,mjs}"] } }));

module.exports = config
